In [1]:
import pandas as pd

In [2]:
data_import = pd.read_csv('test_data.csv')
data_import

,Date,Ordered Product Sales,Units Ordered,Total Order Items,Average Sales per Order Item,Average Units per Order Item,Average Selling Price,Sessions,Order Item Session Percentage,Average Offer Count,Missing Values Column
0,2020-01-03,229.95,0,0,0.00,0.00,0.00,74,0.0000,44,NaN
1,2020-01-15,0.00,0,0,0.00,0.00,0.00,89,0.0000,44,0.0
2,2020-01-17,0.00,0,0,0.00,0.00,0.00,92,0.0000,44,0.0
3,2020-01-19,0.00,0,0,0.00,0.00,0.00,116,0.0000,44,0.0
4,2020-01-25,0.00,0,0,0.00,0.00,0.00,108,0.0000,44,0.0
...,...,...,...,...,...,...,...,...,...,...,...
86,2020-03-31,214.77,8,5,42.95,1.60,26.85,88,0.0568,48,8.0
87,2020-03-24,244.79,10,5,48.96,2.00,24.48,121,0.0413,45,10.0
88,2020-03-12,449.87,13,3,149.96,4.33,34.61,75,0.0400,43,13.0
89,2020-03-19,449.65,15,8,56.21,1.88,29.98,82,0.0976,43,15.0
90,2020-03-13,727.69,19,7,103.96,2.71,38.30,52,0.1346,43,19.0